# Generated by Django 5.2.8 on 2026-09-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILED", "Login Failed"),
                    ("APPOINTMENT_BOOKED", "Appointment Booked"),
                    ("APPOINTMENT_CANCELLED", "Appointment Cancelled"),
                    ("DOCTOR_APPROVED", "Doctor Approved"),
                    ("REPORT_UPLOADED", "Report Uploaded"),
                    ("CONSULTATION_COMPLETED", "Consultation Completed"),
                    ("INVOICE_PAID", "Invoice Paid"),
                    ("KB_DOCUMENT_UPLOADED", "KB Document Uploaded"),
                    ("KB_DOCUMENT_DELETED", "KB Document Deleted"),
                ],
                max_length=50,
            ),
        ),
    ]
