# Generated by Django 5.2.8 on 2026-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_seed_departments"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("AMBULANCE", "Ambulance"),
                            ("EMERGENCY_DEPT", "Emergency Department"),
                            ("HELPLINE", "Helpline"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
