# Generated by Django 5.2.8 on 2026-09-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("qualification", models.CharField(max_length=255)),
                (
                    "available_time",
                    models.CharField(default="Mon-Sat, 9AM-5PM", max_length=255),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="departments.department",
                    ),
                ),
            ],
        ),
    ]
